export const characteristicsMapping = {
    model: 'Modelo',
    socket: 'Socket',
    cores: 'Núcleos',
    frequency: 'Frecuencia',
    fabrication_proccess: 'Proceso De Fabricación',
    gpu_chipset: 'Chipset GPU',
    threads: 'Hilos',
    turbo_frequency: 'Frecuencia Turbo',
    family: 'Familia',
    platform: 'Plataforma',
    principal_chipset: 'Chipstet Principal',
    bios_flashback_button: 'Botón Bios Flashback',
    fans_amount: 'Cantidad De Fans',
    size: 'Tamaño',
    pad_size: 'Tamaño',
    thickness: 'Espesor',
    gpu_thickness: 'Espesor',
    energy: 'Consumo',
    length: 'Largo',
    width: 'Ancho',
    height: 'Alto',
    capacity: 'Capacidad',
    speed: 'Velocidad',
    type: 'Tipo',
    memories_amount: 'Cantidad De Memorias',
    latency: 'Latencia',
    voltage: 'Voltaje',
    video_entry: 'Entrada De Video',
    doble_bridge: 'Doble Puente',
    connection_type: 'Tipo De Conexión',
    disk_type: 'Tipo De Disco',
    nominal_watts: 'Watts Nominales',
    real_watts: 'Watts Reales',
    format: 'Formato',
    lower_compatible: 'Compatible Con Posición Inferior',
    certification: 'Certificación 80 Plus',
    hybrid_mode: 'Modo Híbrido',
    wiring_type: 'Tipo De Cableado',
    inline_amperes: 'Ampers En Línea +12V',
    digital_font: 'Fuente Digital',
    color: 'Color',
    ilumination: 'Iluminación',
    mother_factor: 'Factor Mother',
    superior_font: 'Fuente En Posición Superior',
    with_window: 'Con Ventana',
    window_type: 'Tipo De Ventana',
    processor: 'Procesador',
    motherboard: 'Placa Madre',
    memories: 'Memoria RAM',
    cooler: 'Cooler',
    graphic_card: 'Placa De Video',
    ssd: 'Disco Sólido',
    hdd: 'Disco Duro',
    power_supply: 'Fuente De Poder',
    case: 'Gabinete',
    gpu_model: 'Modelo De GPU',
    os: 'Sistema Operativo',
    ram_memory: 'Memoria RAM',
    ssd_capacity: 'Capacidad De Disco Sólido',
    resolution: 'Resolución De Pantalla',
    screen_size: 'Tamaño De Pantalla',
    update_freq: 'Frecuencia De Actualización',
    weight: 'Peso',
    notebook_weight: 'Peso',
    keyboard_type: 'Tipo De Teclado',
    language: 'Idioma',
    mechanism: 'Tipo De Mecanismo',
    material: 'Material',
    numeric_pad: 'Pad Numérico',
    buttons_amount: 'Cantidad De Botones',
    sensor_type: 'Tipo De Sensor',
    wireless: 'Inalámbrico',
    detachable_cable: 'Cable Desmontable',
    adjustable_dpi: 'DPI Ajustable',
    minimum_dpi: 'DPI Mínimo',
    maximum_dpi: 'DPI Máximo',
    response_frequency: 'Frecuencia De Respuesta',
    surface_type: 'Tipo De Superficie',
    sliding_type: 'Tipo De Desplazamiento',
    audio: 'Audio',
    microphone: 'Micrófono',
    audio_type: 'Tipo De Audio',
    ilumination_type: 'Tipo De Iluminación',
    panel_type: 'Tipo De Panel',
    curved_screen: 'Pantalla Curva',
    brand: 'Marca',
    storage: 'Almacenamiento',
    os_version: 'Versión Del Sistema Operativo',
    water_resistance: 'Resistencia A Salpicaduras'
}