export const characUnits = {
    frequency: 'MHz',
    fabrication_proccess: 'nm',
    turbo_frequency: 'MHz',
    capacity: 'GB',
    speed: 'MHz',
    latency: 'CL',
    voltage: 'V',
    size: 'mm',
    thickness: 'mm',
    energy: 'W',
    length: 'mm',
    width: 'mm',
    height: 'mm',
    gpu_thickness: ' slots',
    nominal_watts: 'W',
    real_watts: 'W',
    inline_amperes: 'a',
    ram_memory: 'GB',
    ssd_capacity: 'GB',
    screen_size: "''",
    update_freq: 'Hz',
    notebook_weight: 'kg',
    response_frequency: 'Hz',
    storage: 'GB'
}